BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_OKR_OBJETIVOS_MEDICIONES" start with 1';

execute immediate 'CREATE TABLE "OKR_OBJETIVOS_MEDICIONES" (
    "OBJETIVO_MEDICION_ID" NUMBER(19) NOT NULL,
    "OBJETIVO_ID" NUMBER(19) NOT NULL,
    "TIPO_MEDICION_ID" NUMBER(10),
    "MEDICION_BINARIA" NUMBER(1) NOT NULL,
    "VALOR_MAXIMO_MEDICION" NUMBER(18,2),
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT "PK_OKR_OBJETIVOS_MEDICIONES" PRIMARY KEY ("OBJETIVO_MEDICION_ID"),
    CONSTRAINT "FK_OKR_OBJETIVOS_MEDICIONES_TIPOS_MEDICION" FOREIGN KEY ("TIPO_MEDICION_ID") REFERENCES "OKR_CAT_TIPOS_MEDICION" ("TIPO_MEDICION_ID"),
    CONSTRAINT "FK_OKR_OBJETIVOS_OBJETIVOS_MEDICIONES" FOREIGN KEY ("OBJETIVO_ID") REFERENCES "OKR_OBJETIVOS" ("OBJETIVO_ID") ON DELETE CASCADE
)';
execute immediate 'create or replace trigger "TR_OKR_OBJETIVOS_MEDICIONES"
before insert on "OKR_OBJETIVOS_MEDICIONES" for each row 
begin 
  if :new."OBJETIVO_MEDICION_ID" is NULL then 
    select "SQ_OKR_OBJETIVOS_MEDICIONES".nextval into :new."OBJETIVO_MEDICION_ID" from dual;  
  end if; 
end;';
END;
/

CREATE INDEX "IX_OKR_OBJETIVOS_MEDICIONES_OBJETIVO_ID" ON "OKR_OBJETIVOS_MEDICIONES" ("OBJETIVO_ID")
/

CREATE INDEX "IX_OKR_OBJETIVOS_MEDICIONES_TIPO_MEDICION_ID" ON "OKR_OBJETIVOS_MEDICIONES" ("TIPO_MEDICION_ID")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220218185910_AddOKR_OBJETIVOS_MEDICIONES', N'5.0.12')
/

insert into OKR_OBJETIVOS_MEDICIONES ( OBJETIVO_ID, TIPO_MEDICION_ID, MEDICION_BINARIA, VALOR_MAXIMO_MEDICION, LAST_UPDATE, ACTIVE_FLAG)
select objetivo_id, tipo_medicion_id, 0 as MEDICION_BINARIA, valor_maximo_medicion, LAST_UPDATE, active_flag
from okr_objetivos
where active_flag = 1
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220218192317_PopulateOKR_OBJETIVOS_MEDICIONES', N'5.0.12')
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'OKR_OBJETIVOS_MEDICIONES' 
  and column_name = 'MEDICION_BINARIA' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "OKR_OBJETIVOS_MEDICIONES" MODIFY "MEDICION_BINARIA" NUMBER(1) DEFAULT 0 ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "OKR_OBJETIVOS_MEDICIONES" MODIFY "MEDICION_BINARIA" NUMBER(1) DEFAULT 0 NOT NULL';
 end if;
end;
/

ALTER TABLE "OKR_OBJETIVOS_MEDICIONES" ADD "PONDERACION_MEDICION" NUMBER(18,2)
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220306155636_ObjetivoMediciones', N'5.0.12')
/

