ALTER TABLE SL_EDOCTA_DCF
  ADD (META_SEGUROS NUMBER(25, 2),
       REAL_SEGUROS NUMBER(25, 2),
       EXCEDENTE_SEGUROS NUMBER(25, 2),
       CUMPLIMIENTO_SEGUROS NUMBER(8, 4),
       ALCANCE_SEGUROS NUMBER(8, 4),
       PAGO_SEGUROS NUMBER(25,2),
       META_CREDITO NUMBER(25,2),
       REAL_CREDITO NUMBER(25,2),
       EXCEDENTE_CREDITO NUMBER(25, 2),
       CUMPLIMIENTO_CREDITO NUMBER(8,4),
       ALCANCE_CREDITO NUMBER(8,4),
       PAGO_CREDITOS NUMBER(25, 2),       
       CREDITOS_NEGOCIO NUMBER(25, 2),
       SEGUROS_NEGOCIO NUMBER(25, 2),
       ALCANCE_TOTAL_SCORECARD NUMBER(8, 4),
       COMISION NUMBER(25, 2));
       
       
       select * from sl_edocta_dcf;
       
  
  
  