BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_CAT_DIAS_HOME_OFFICE" start with 1';

execute immediate 'CREATE TABLE "TF_CAT_DIAS_HOME_OFFICE" (
    "DIA_HOME_OFFICE_ID" NUMBER(19) NOT NULL,
    "DESCRIPCION" NVARCHAR2(255) NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_DIAS_HOME_OFFICE" PRIMARY KEY ("DIA_HOME_OFFICE_ID")
)';
execute immediate 'create or replace trigger "TR_TF_CAT_DIAS_HOME_OFFICE"
before insert on "TF_CAT_DIAS_HOME_OFFICE" for each row 
begin 
  if :new."DIA_HOME_OFFICE_ID" is NULL then 
    select "SQ_TF_CAT_DIAS_HOME_OFFICE".nextval into :new."DIA_HOME_OFFICE_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_CAT_ESTATUS_CUESTIONARIO" start with 1';

execute immediate 'CREATE TABLE "TF_CAT_ESTATUS_CUESTIONARIO" (
    "ESTATUS_CUESTIONARIO_ID" NUMBER(19) NOT NULL,
    "DESCRIPCION" NVARCHAR2(255) NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_ESTATUS_CUESTIONARIO" PRIMARY KEY ("ESTATUS_CUESTIONARIO_ID")
)';
execute immediate 'create or replace trigger "TR_TF_CAT_ESTATUS_CUESTIONARIO"
before insert on "TF_CAT_ESTATUS_CUESTIONARIO" for each row 
begin 
  if :new."ESTATUS_CUESTIONARIO_ID" is NULL then 
    select "SQ_TF_CAT_ESTATUS_CUESTIONARIO".nextval into :new."ESTATUS_CUESTIONARIO_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_CAT_PREGUNTAS" start with 1';

execute immediate 'CREATE TABLE "TF_CAT_PREGUNTAS" (
    "PREGUNTA_ID" NUMBER(19) NOT NULL,
    "DESCRIPCION" NCLOB NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_TF_PREGUNTAS" PRIMARY KEY ("PREGUNTA_ID")
)';
execute immediate 'create or replace trigger "TR_TF_CAT_PREGUNTAS"
before insert on "TF_CAT_PREGUNTAS" for each row 
begin 
  if :new."PREGUNTA_ID" is NULL then 
    select "SQ_TF_CAT_PREGUNTAS".nextval into :new."PREGUNTA_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_EMPLEADO_DIAS_HO_XREF" start with 1';

execute immediate 'CREATE TABLE "TF_EMPLEADO_DIAS_HO_XREF" (
    "EMPLEADO_DIA_HO_ID" NUMBER(19) NOT NULL,
    "EMPLEADO_ID" NUMBER(18,0) NOT NULL,
    "DIA_HOME_OFFICE_ID" NUMBER(18,0) NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_EMPLEADO_DIAS_HO" PRIMARY KEY ("EMPLEADO_DIA_HO_ID"),
    CONSTRAINT "FK_DIA_HO_EMPLEADO_XREF" FOREIGN KEY ("DIA_HOME_OFFICE_ID") REFERENCES "TF_CAT_DIAS_HOME_OFFICE" ("DIA_HOME_OFFICE_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_EMPLEADO_DIAS_HO_XREF" FOREIGN KEY ("EMPLEADO_ID") REFERENCES "OKR_EMPLEADOS" ("EMPLEADO_ID") ON DELETE CASCADE
)';
execute immediate 'create or replace trigger "TR_TF_EMPLEADO_DIAS_HO_XREF"
before insert on "TF_EMPLEADO_DIAS_HO_XREF" for each row 
begin 
  if :new."EMPLEADO_DIA_HO_ID" is NULL then 
    select "SQ_TF_EMPLEADO_DIAS_HO_XREF".nextval into :new."EMPLEADO_DIA_HO_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_CUESTIONARIO_EMPLEADO" start with 1';

execute immediate 'CREATE TABLE "TF_CUESTIONARIO_EMPLEADO" (
    "CUESTIONARIO_EMPLEADO_ID" NUMBER(19) NOT NULL,
    "EMPLEADO_ID" NUMBER(18,0) NOT NULL,
    "ESTATUS_CUESTIONARIO_ID" NUMBER(18,0) NOT NULL,
    "HAS_EXCEPTION" NUMBER(1) DEFAULT 0 NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    "DATE_INSERT" TIMESTAMP(7),
    CONSTRAINT "PK_CUESTIONARIO_EMPLEADO" PRIMARY KEY ("CUESTIONARIO_EMPLEADO_ID"),
    CONSTRAINT "FK_EMPLEADO_CUESTIONARIO_XREF" FOREIGN KEY ("EMPLEADO_ID") REFERENCES "OKR_EMPLEADOS" ("EMPLEADO_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ESTATUS_CUESTIONARIO" FOREIGN KEY ("ESTATUS_CUESTIONARIO_ID") REFERENCES "TF_CAT_ESTATUS_CUESTIONARIO" ("ESTATUS_CUESTIONARIO_ID") ON DELETE CASCADE
)';
execute immediate 'create or replace trigger "TR_TF_CUESTIONARIO_EMPLEADO"
before insert on "TF_CUESTIONARIO_EMPLEADO" for each row 
begin 
  if :new."CUESTIONARIO_EMPLEADO_ID" is NULL then 
    select "SQ_TF_CUESTIONARIO_EMPLEADO".nextval into :new."CUESTIONARIO_EMPLEADO_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_CUESTIONARIO__1717693534" start with 1';

execute immediate 'CREATE TABLE "TF_CUESTIONARIO_PREGUNTAS_XREF" (
    "CUESTIONARIO_PREGUNTAS_ID" NUMBER(19) NOT NULL,
    "CUESTIONARIO_EMPLEADO_ID" NUMBER(18,0) NOT NULL,
    "PREGUNTA_ID" NUMBER(18,0) NOT NULL,
    "CALIFICACION" NUMBER(1) DEFAULT 0 NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_CUESTIONARIO_PREGUNTAS" PRIMARY KEY ("CUESTIONARIO_PREGUNTAS_ID"),
    CONSTRAINT "FK_CUESTIONARIO_PREGUNTA_XREF" FOREIGN KEY ("CUESTIONARIO_EMPLEADO_ID") REFERENCES "TF_CUESTIONARIO_EMPLEADO" ("CUESTIONARIO_EMPLEADO_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_PREGUNTA_CUESTIONARIO_XREF" FOREIGN KEY ("PREGUNTA_ID") REFERENCES "TF_CAT_PREGUNTAS" ("PREGUNTA_ID") ON DELETE CASCADE
)';
execute immediate 'create or replace trigger "TR_TF_CUESTIONARIO__1719657673"
before insert on "TF_CUESTIONARIO_PREGUNTAS_XREF" for each row 
begin 
  if :new."CUESTIONARIO_PREGUNTAS_ID" is NULL then 
    select "SQ_TF_CUESTIONARIO__1717693534".nextval into :new."CUESTIONARIO_PREGUNTAS_ID" from dual;  
  end if; 
end;';
END;
/

BEGIN 

execute immediate 'CREATE SEQUENCE "SQ_TF_EMPLEADO_CONSIDERACION" start with 1';

execute immediate 'CREATE TABLE "TF_EMPLEADO_CONSIDERACION" (
    "EMPLEADO_CONSIDERACION_ID" NUMBER(19) NOT NULL,
    "DESCRIPCION" NCLOB NOT NULL,
    "CUESTIONARIO_EMPLEADO_ID" NUMBER(18,0) NOT NULL,
    "ACTIVE_FLAG" NUMBER(1) DEFAULT 1 NOT NULL,
    "LAST_UPDATE" TIMESTAMP(7) DEFAULT (sysdate) NOT NULL,
    CONSTRAINT "PK_EMPLEADO_CONSIDERACION" PRIMARY KEY ("EMPLEADO_CONSIDERACION_ID"),
    CONSTRAINT "FK_EMPLEADO_CONSIDERACION" FOREIGN KEY ("EMPLEADO_CONSIDERACION_ID") REFERENCES "TF_CUESTIONARIO_EMPLEADO" ("CUESTIONARIO_EMPLEADO_ID") ON DELETE CASCADE
)';
execute immediate 'create or replace trigger "TR_TF_EMPLEADO_CONSIDERACION"
before insert on "TF_EMPLEADO_CONSIDERACION" for each row 
begin 
  if :new."EMPLEADO_CONSIDERACION_ID" is NULL then 
    select "SQ_TF_EMPLEADO_CONSIDERACION".nextval into :new."EMPLEADO_CONSIDERACION_ID" from dual;  
  end if; 
end;';
END;
/

CREATE INDEX "IX_TF_CUESTIONARIO_EMPLEADO_EMPLEADO_ID" ON "TF_CUESTIONARIO_EMPLEADO" ("EMPLEADO_ID")
/

CREATE INDEX "IX_TF_CUESTIONARIO_EMPLEADO_ESTATUS_CUESTIONARIO_ID" ON "TF_CUESTIONARIO_EMPLEADO" ("ESTATUS_CUESTIONARIO_ID")
/

CREATE INDEX "IX_TF_CUESTIONARIO_PREGUNTAS_XREF_CUESTIONARIO_EMPLEADO_ID" ON "TF_CUESTIONARIO_PREGUNTAS_XREF" ("CUESTIONARIO_EMPLEADO_ID")
/

CREATE INDEX "IX_TF_CUESTIONARIO_PREGUNTAS_XREF_PREGUNTA_ID" ON "TF_CUESTIONARIO_PREGUNTAS_XREF" ("PREGUNTA_ID")
/

CREATE INDEX "IX_TF_EMPLEADO_DIAS_HO_XREF_DIA_HOME_OFFICE_ID" ON "TF_EMPLEADO_DIAS_HO_XREF" ("DIA_HOME_OFFICE_ID")
/

CREATE INDEX "IX_TF_EMPLEADO_DIAS_HO_XREF_EMPLEADO_ID" ON "TF_EMPLEADO_DIAS_HO_XREF" ("EMPLEADO_ID")
/

INSERT INTO TF_CAT_PREGUNTAS (Descripcion) VALUES ('¿Es candidato a home office por función / tipo de actividad?')
/

INSERT INTO TF_CAT_PREGUNTAS (Descripcion) VALUES ('¿Es candidato a home office por madurez y desempeño?')
/

INSERT INTO TF_CAT_PREGUNTAS (Descripcion) VALUES ('¿Tiene las condiciones en su hogar para hacer home office?')
/

INSERT INTO TF_CAT_ESTATUS_CUESTIONARIO (descripcion) VALUES ('Pendiente')
/

INSERT INTO TF_CAT_ESTATUS_CUESTIONARIO (descripcion) VALUES ('Autorizado')
/

INSERT INTO TF_CAT_ESTATUS_CUESTIONARIO (descripcion) VALUES ('No Autorizado')
/

INSERT INTO TF_CAT_ESTATUS_CUESTIONARIO (descripcion) VALUES ('Autorizado Extraordinario')
/

INSERT INTO TF_CAT_ESTATUS_CUESTIONARIO (descripcion) VALUES ('No Autorizado Extraordinario')
/

INSERT INTO TF_CAT_DIAS_HOME_OFFICE (descripcion) VALUES ('Lunes')
/

INSERT INTO TF_CAT_DIAS_HOME_OFFICE (descripcion) VALUES ('Martes')
/

INSERT INTO TF_CAT_DIAS_HOME_OFFICE (descripcion) VALUES ('Miercoles')
/

INSERT INTO TF_CAT_DIAS_HOME_OFFICE (descripcion) VALUES ('Jueves')
/

INSERT INTO TF_CAT_DIAS_HOME_OFFICE (descripcion) VALUES ('Viernes')
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220526005205_InitTrabajoFlexible', N'5.0.12')
/

ALTER TABLE "TF_EMPLEADO_CONSIDERACION" DROP CONSTRAINT "FK_EMPLEADO_CONSIDERACION"
/

CREATE UNIQUE INDEX "IX_TF_EMPLEADO_CONSIDERACION_CUESTIONARIO_EMPLEADO_ID" ON "TF_EMPLEADO_CONSIDERACION" ("CUESTIONARIO_EMPLEADO_ID")
/

ALTER TABLE "TF_EMPLEADO_CONSIDERACION" ADD CONSTRAINT "FK_EMPLEADO_CONSIDERACION" FOREIGN KEY ("CUESTIONARIO_EMPLEADO_ID") REFERENCES "TF_CUESTIONARIO_EMPLEADO" ("CUESTIONARIO_EMPLEADO_ID") ON DELETE CASCADE
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220530212649_FixFKCEmpleadoConsideracion', N'5.0.12')
/

