--------------------------------------------------------
-- Archivo creado  - miércoles-febrero-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OKR_CAT_DIRECCIONES_EJECUTIVAS
--------------------------------------------------------

  CREATE TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" 
   (	"DIRECCION_EJECUTIVA_ID" NUMBER(10,0), 
	"NUM_DIRECCION_EJECUTIVA" NUMBER(19,0), 
	"DESCRIPCION" NVARCHAR2(255), 
	"LAST_UPDATE" TIMESTAMP (7) DEFAULT (sysdate), 
	"ACTIVE_FLAG" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CDO_APP" ;
REM INSERTING into OKR_CAT_DIRECCIONES_EJECUTIVAS
SET DEFINE OFF;
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (41,1108,'COMITE ARRENDADORA',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (42,1110,'COMITE ASSET MANAGEMENT',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (43,1111,'COMITE CREDITO',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (44,165,'COMITE PREVISION SOCIAL',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (45,1109,'COMITE RIESGOS',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (46,1112,'COMITE SEGUROS',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (47,696,'DIR. EJEC. BANCA CORPORATIVA Y BANCA DE INVERSION',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (48,954,'DIR. EJEC. CANALES DIGITALES',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (49,1030,'DIR. EJEC. CAPITAL HUMANO',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (50,1035,'DIR. EJEC. ESTRATEGIA TRANSFORMACION Y MERCADOTECNIA',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (51,28,'DIR. EJEC. JURIDICO',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (52,961,'DIR. EJEC. MERCADOS Y TESORERIA',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (53,640,'DIR. EJEC. OPERACIONES Y FINANZAS',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (54,657,'DIR. EJEC. PROMOCION Y ASESORIA',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (55,927,'DIR. EJEC. TECNOLOGIAS DE LA INFORMACION',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (56,0,'DIRECCION GENERAL ADJUNTA JPV',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (57,0,'DIRECCION GENERAL ADJUNTA RV',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (58,0,'DIRECCION GENERAL HM',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into OKR_CAT_DIRECCIONES_EJECUTIVAS (DIRECCION_EJECUTIVA_ID,NUM_DIRECCION_EJECUTIVA,DESCRIPCION,LAST_UPDATE,ACTIVE_FLAG) values (59,0,'SEGURIDAD INFORMATICA',to_timestamp('06/01/22 18:58:58.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
--------------------------------------------------------
--  DDL for Index PK_OKR_CAT_DIRECCIONES_EJECUTIVAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_OKR_CAT_DIRECCIONES_EJECUTIVAS" ON "OKR_CAT_DIRECCIONES_EJECUTIVAS" ("DIRECCION_EJECUTIVA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CDO_APP" ;
--------------------------------------------------------
--  DDL for Trigger TR_OKR_CAT_DIRECCIO_1870397342
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_OKR_CAT_DIRECCIO_1870397342" 
before insert on "OKR_CAT_DIRECCIONES_EJECUTIVAS" for each row 
begin 
  if :new."DIRECCION_EJECUTIVA_ID" is NULL then 
    select "SQ_OKR_CAT_DIRECCION_551872949".nextval into :new."DIRECCION_EJECUTIVA_ID" from dual;  
  end if; 
end;
/
ALTER TRIGGER "TR_OKR_CAT_DIRECCIO_1870397342" ENABLE;
--------------------------------------------------------
--  Constraints for Table OKR_CAT_DIRECCIONES_EJECUTIVAS
--------------------------------------------------------

  ALTER TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" MODIFY ("DIRECCION_EJECUTIVA_ID" NOT NULL ENABLE);
  ALTER TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" MODIFY ("ACTIVE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "OKR_CAT_DIRECCIONES_EJECUTIVAS" ADD CONSTRAINT "PK_OKR_CAT_DIRECCIONES_EJECUTIVAS" PRIMARY KEY ("DIRECCION_EJECUTIVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CDO_APP"  ENABLE;
