create or replace NONEDITIONABLE PROCEDURE SP_TF_EMPLEADOS_DETALLE
( 
  DATE_PARAM DATE,
  CUR_PARAM OUT sys_REFCURSOR
)
AS
BEGIN
  OPEN CUR_PARAM FOR 
    SELECT 

        TBEJ.EMPLEADO_id                        AS "EMPLEADO_JEFE_ID",
        TBEJ.NUM_EMPLEADO               AS "NUMERO_EMPLEADO_JEFE",
        TBEJ.NOMBRE                     AS "NOMBRE_EMPLEADO_JEFE",
        EMP.EMPLEADO_ID, 
        EMP.NUM_EMPLEADO, 
        EMP.NOMBRE         AS "NOMBRE_EMPLEADO", 
        emp.email    AS "EMAIL_EMPLEADO",
        AREA.AREA_ID, 
        AREA.NUM_AREA    AS "NUMERO_AREA", 
        AREA.DESCRIPCION AS "AREA_DESCRIPCION", 
        CF.CENTRO_FINANCIERO_ID   AS "CENTRO_FINANCIERO_ID", 
        CF.NUM_CF   AS "NUMERO_CENTRO_FINANCIERO", 
        CF.DESCRIPCION AS "CENTRO_FINANCIERO", 
        DE.DIRECCION_EJECUTIVA_ID, 
        DE.NUM_DIRECCION_EJECUTIVA  AS "NUMERO_DIRECCION_EJECUTIVA", 
        DE.DESCRIPCION AS DIRECCION_EJECUTIVA, 
        P.PUESTO_ID, 
        P.NUM_PUESTO as "NUMERO_PUESTO", 
        P.DESCRIPCION AS "PUESTO_DESCRIPCION",
        EMP.AVATAR,
        tbeva.EVALUACION_ESTATUS_ID,
        tbeva.TOTAL_CALIFICACION,
        tbr.Cerrada

    FROM OKR_EMPLEADOS EMP
    LEFT JOIN OKR_EMPLEADO_AREA_XREF EMPA ON EMP.EMPLEADO_ID = EMPA.EMPLEADO_ID
                                AND EMPA.ACTIVE_FLAG = 1
                                AND EMPA.FECHA_ALTA <= DATE_PARAM AND (EMPA.FECHA_BAJA IS NULL OR EMPA.FECHA_BAJA >= DATE_PARAM)
    LEFT JOIN OKR_CAT_AREAS AREA ON EMPA.AREA_ID = AREA.AREA_ID
    LEFT JOIN OKR_EMPLEADO_CENTRO_FINANCIERO_XREF EMPCF ON EMP.EMPLEADO_ID = EMPCF.EMPLEADO_ID
                                AND EMPCF.ACTIVE_FLAG = 1
                                AND EMPCF.FECHA_ALTA <= DATE_PARAM AND (EMPCF.FECHA_BAJA IS NULL OR EMPCF.FECHA_BAJA >= DATE_PARAM)
    LEFT JOIN OKR_CAT_CENTROS_FINANCIEROS CF ON EMPCF.CENTRO_FINANCIERO_ID = CF.CENTRO_FINANCIERO_ID
    LEFT JOIN OKR_EMPLEADO_DIR_EJEC_XREF EMPDE ON EMP.EMPLEADO_ID = EMPDE.EMPLEADO_ID
                                AND EMPDE.ACTIVE_FLAG = 1
                                AND EMPDE.FECHA_ALTA <= DATE_PARAM AND (EMPDE.FECHA_BAJA IS NULL OR EMPDE.FECHA_BAJA >= DATE_PARAM)
    LEFT JOIN OKR_CAT_DIRECCIONES_EJECUTIVAS DE ON EMPDE.DIRECCION_EJECUTIVA_ID = DE.DIRECCION_EJECUTIVA_ID
    LEFT JOIN OKR_EMPLEADO_PUESTO_XREF EMPP ON EMP.EMPLEADO_ID = EMPP.EMPLEADO_ID
                                AND EMPP.ACTIVE_FLAG = 1
                                AND EMPP.FECHA_ALTA <= DATE_PARAM AND (EMPP.FECHA_BAJA IS NULL OR EMPP.FECHA_BAJA >= DATE_PARAM)
    LEFT JOIN OKR_CAT_PUESTOS P ON EMPP.PUESTO_ID = P.PUESTO_ID
    INNER JOIN okr_empleado_reporta_xref  TBER ON EMP.EMPLEADO_ID =  TBER.EMPLEADO_ID
    INNER JOIN OKR_EMPLEADOS        TBEJ    ON TBEJ.EMPLEADO_ID = tber.reporta_id
    inner join okr_evaluacion_empleado_xref TBEVAEMP on tbevaemp.empleado_id = emp.empleado_id 
    inner join okr_evaluacion tbeva on tbeva.evaluacion_id = tbevaemp.evaluacion_id and tbeva.autoevaluacion = 1
    inner join okr_retroalimentacion tbr  on tbr.empleado_id = emp.empleado_id and tbr.cerrada = 1
    WHERE EMP.ACTIVE_FLAG = 1
    GROUP BY     
        EMP.EMPLEADO_ID, 
        EMP.NUM_EMPLEADO, 
        EMP.NOMBRE, 
        AREA.AREA_ID, 
        AREA.NUM_AREA, 
        AREA.DESCRIPCION, 
        CF.CENTRO_FINANCIERO_ID, 
        CF.NUM_CF, 
        CF.DESCRIPCION, 
        DE.DIRECCION_EJECUTIVA_ID, 
        DE.NUM_DIRECCION_EJECUTIVA, 
        DE.DESCRIPCION, 
        P.PUESTO_ID, 
        P.NUM_PUESTO, 
        P.DESCRIPCION,
        TBEJ.EMPLEADO_id,
        TBEJ.NUM_EMPLEADO,
        TBEJ.NOMBRE,
        emp.email,
        EMP.AVATAR,
        tbeva.EVALUACION_ESTATUS_ID,
        tbr.Cerrada,
        tbeva.TOTAL_CALIFICACION;
END;
