  CREATE TABLE TF_CUESTIONAIRO_EMP_LOG
   (	
    "ID" NUMBER(25,0) DEFAULT "SEQ_LOG_CUESTIONARIO_EMP"."NEXTVAL", 
	"CUESTIONARIO_EMPLEADO_ID" NUMBER(18,0), 
	"EMPLEADO_ID" NUMBER(18,0), 
	"ESTATUS_CUESTIONARIO_ID" NUMBER(18,0), 
	"HAS_EXCEPTION" NUMBER(1,0) DEFAULT 0, 
	"LAST_UPDATE" TIMESTAMP (7) DEFAULT SYSDATE
   );
   
CREATE UNIQUE INDEX "PK_CUESTIONARIO_EMP_LOG" ON "TF_CUESTIONAIRO_EMP_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("CUESTIONARIO_EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("ESTATUS_CUESTIONARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("HAS_EXCEPTION" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "TF_CUESTIONAIRO_EMP_LOG" ADD CONSTRAINT "PK_CUESTIONARIO_EMP_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  
  CREATE OR REPLACE NONEDITIONABLE TRIGGER "CDO_OKR"."TRG_LOG_CUESTIONARIO_EMP" 
AFTER UPDATE 
  OF ESTATUS_CUESTIONARIO_ID, HAS_EXCEPTION 
    ON TF_CUESTIONARIO_EMPLEADO 
FOR EACH ROW
BEGIN
    -- Insert new values into log table.
    INSERT INTO TF_CUESTIONAIRO_EMP_LOG 
    (CUESTIONARIO_EMPLEADO_ID, EMPLEADO_ID, ESTATUS_CUESTIONARIO_ID, HAS_EXCEPTION, LAST_UPDATE)
    VALUES (
		:NEW.CUESTIONARIO_EMPLEADO_ID, :NEW.EMPLEADO_ID, :OLD.ESTATUS_CUESTIONARIO_ID, :OLD.HAS_EXCEPTION, SYSDATE);
END;
